
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import project1.ConnectionProvider;
import java.sql.*;
import project1.ConnectionProvider;
import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shiva
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MechanicTableDisplay = new javax.swing.JTable();
        DeleteMechAdmin2 = new javax.swing.JButton();
        AdminHomeMech = new javax.swing.JButton();
        AdminHomeUser = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        AdminViewUser = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        AdminUpdateMech = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        UserTableDisplay = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        UserDeleteAdmin = new javax.swing.JTextField();
        AdminViewMech = new javax.swing.JButton();
        MechDeleteAdmin = new javax.swing.JTextField();
        DeleteUserAdmin1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        MechanicTableDisplay.setForeground(new java.awt.Color(51, 204, 0));
        MechanicTableDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "mechanic name", "mechanic id", "mechanic shop", "mechanic phone", "mech_pincode"
            }
        ));
        jScrollPane1.setViewportView(MechanicTableDisplay);

        DeleteMechAdmin2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DeleteMechAdmin2.setForeground(new java.awt.Color(255, 0, 0));
        DeleteMechAdmin2.setText("Delete");
        DeleteMechAdmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteMechAdmin2ActionPerformed(evt);
            }
        });

        AdminHomeMech.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AdminHomeMech.setForeground(new java.awt.Color(0, 0, 204));
        AdminHomeMech.setText("Home");
        AdminHomeMech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminHomeMechActionPerformed(evt);
            }
        });

        AdminHomeUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AdminHomeUser.setForeground(new java.awt.Color(0, 0, 204));
        AdminHomeUser.setText("Home");
        AdminHomeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminHomeUserActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Mechanic list");

        AdminViewUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AdminViewUser.setText("View");
        AdminViewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminViewUserActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("User list");

        AdminUpdateMech.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AdminUpdateMech.setForeground(new java.awt.Color(204, 153, 0));
        AdminUpdateMech.setText("Update");
        AdminUpdateMech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminUpdateMechActionPerformed(evt);
            }
        });

        UserTableDisplay.setForeground(new java.awt.Color(51, 255, 0));
        UserTableDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User Name", "User id", "Phone Num", "email"
            }
        ));
        jScrollPane2.setViewportView(UserTableDisplay);

        jLabel4.setText("Enter User Id");

        jLabel5.setText("Enter Mechanic Id");

        UserDeleteAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserDeleteAdminActionPerformed(evt);
            }
        });

        AdminViewMech.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AdminViewMech.setText("View");
        AdminViewMech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminViewMechActionPerformed(evt);
            }
        });

        DeleteUserAdmin1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DeleteUserAdmin1.setForeground(new java.awt.Color(255, 0, 0));
        DeleteUserAdmin1.setText("Delete");
        DeleteUserAdmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteUserAdmin1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MechDeleteAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteMechAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AdminViewMech, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AdminUpdateMech, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AdminHomeMech, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(UserDeleteAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteUserAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AdminViewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AdminHomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1008, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UserDeleteAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DeleteUserAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AdminViewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AdminHomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MechDeleteAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteMechAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminViewMech, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminUpdateMech, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminHomeMech, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminHomeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminHomeUserActionPerformed
        // TODO add your handling code here:
        setVisible(false);
            new index().setVisible(true);
    }//GEN-LAST:event_AdminHomeUserActionPerformed

    private void AdminHomeMechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminHomeMechActionPerformed
        // TODO add your handling code here:
        setVisible(false);
            new index().setVisible(true);
    }//GEN-LAST:event_AdminHomeMechActionPerformed

    private void AdminViewMechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminViewMechActionPerformed
        try
        {
            Connection con=ConnectionProvider.getcon();
            Statement st=con.createStatement();
            ResultSet rs = st.executeQuery("select mechname as mechanic_name,mechid as mechanic_licence,shopname as mechanic_shop,phoneno as mechanic_phone,pin as pincode from mechanic");
           MechanicTableDisplay.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"CONNECTION NOT ESATABLISHED");
        } // TODO add your h// TODO add your handling code here:
    }//GEN-LAST:event_AdminViewMechActionPerformed

    private void AdminViewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminViewUserActionPerformed
       try
        {
            Connection con=ConnectionProvider.getcon();
            Statement st=con.createStatement();
            ResultSet rs = st.executeQuery("select usname as user_name,usdlno as user_d_licence,usemail as user_email,usphone as user_phone from user");
           UserTableDisplay.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"CONNECTION NOT ESATABLISHED");
        } // TODO add your handling code here:
    }//GEN-LAST:event_AdminViewUserActionPerformed

    private void AdminUpdateMechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminUpdateMechActionPerformed
        // TODO add your handling code here:
        setVisible(false);
            new Update().setVisible(true);
    }//GEN-LAST:event_AdminUpdateMechActionPerformed

    private void DeleteUserAdmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteUserAdmin1ActionPerformed
       try
        {
           Connection con=ConnectionProvider.getcon();
            Statement st=con.createStatement();
            String usdlno=UserDeleteAdmin.getText();
            st.executeUpdate("delete from user where usdlno='"+usdlno+"'");
            JOptionPane.showMessageDialog(null,"successfully deleted");
             Statement stt=con.createStatement();
             ResultSet rs=stt.executeQuery("select usname as user_name,usdlno as user_d_licence,usemail as user_email,usphone as user_phone from user");
             UserTableDisplay.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
 // TODO add your handling code here:
    }//GEN-LAST:event_DeleteUserAdmin1ActionPerformed

    private void UserDeleteAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserDeleteAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserDeleteAdminActionPerformed

    private void DeleteMechAdmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteMechAdmin2ActionPerformed
       try
        {
           Connection con=ConnectionProvider.getcon();
            Statement st=con.createStatement();
            String mechid=MechDeleteAdmin.getText();
            st.executeUpdate("delete from mechanic where mechid='"+mechid+"'");
            JOptionPane.showMessageDialog(null,"successfully deleted");
             Statement stt=con.createStatement();
             ResultSet rs=stt.executeQuery("select mechname as mechanic_name,mechid as mechanic_licence,shopname as mechanic_shop,phoneno as mechanic_phone,pin as pincode from mechanic");
             MechanicTableDisplay.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        } // TODO add your handling code here:
    }//GEN-LAST:event_DeleteMechAdmin2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminHomeMech;
    private javax.swing.JButton AdminHomeUser;
    private javax.swing.JButton AdminUpdateMech;
    private javax.swing.JButton AdminViewMech;
    private javax.swing.JButton AdminViewUser;
    private javax.swing.JButton DeleteMechAdmin2;
    private javax.swing.JButton DeleteUserAdmin1;
    private javax.swing.JTextField MechDeleteAdmin;
    private javax.swing.JTable MechanicTableDisplay;
    private javax.swing.JTextField UserDeleteAdmin;
    private javax.swing.JTable UserTableDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
