/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.s
 */
import java.sql.*;
import project1.ConnectionProvider;
import javax.swing.JOptionPane;
import com.mysql.jdbc.PreparedStatement;
/**
 *
 * @author Shiva
 */
public class MechanicSignUp extends javax.swing.JFrame {

    /**
     * Creates new form MechanicSignUp
     */
    public MechanicSignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MechUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        MechEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        MechPhone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        MechShopName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        MechPinCode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        MechPassword = new javax.swing.JTextField();
        MechCreateAC = new javax.swing.JButton();
        MechSignUpHome = new javax.swing.JButton();
        MechSigninExit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        MechLoginFromSignUp = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Full Name");

        MechUserName.setBackground(new java.awt.Color(255, 255, 204));
        MechUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MechUserNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Licence No");

        MechEmail.setBackground(new java.awt.Color(255, 255, 204));
        MechEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MechEmailActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Phone number");

        MechPhone.setBackground(new java.awt.Color(255, 255, 204));
        MechPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MechPhoneActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Shop Name");

        MechShopName.setBackground(new java.awt.Color(255, 255, 204));
        MechShopName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MechShopNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Pin/Zip Code");

        MechPinCode.setBackground(new java.awt.Color(255, 255, 204));
        MechPinCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MechPinCodeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Password");

        MechPassword.setBackground(new java.awt.Color(255, 255, 204));
        MechPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MechPasswordActionPerformed(evt);
            }
        });

        MechCreateAC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MechCreateAC.setForeground(new java.awt.Color(51, 204, 0));
        MechCreateAC.setText("Create");
        MechCreateAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MechCreateACActionPerformed(evt);
            }
        });

        MechSignUpHome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MechSignUpHome.setText("Home");
        MechSignUpHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MechSignUpHomeActionPerformed(evt);
            }
        });

        MechSigninExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MechSigninExit.setForeground(new java.awt.Color(255, 0, 0));
        MechSigninExit.setText("Exit");
        MechSigninExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MechSigninExitActionPerformed(evt);
            }
        });

        jLabel6.setText("Have an account");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        MechLoginFromSignUp.setText("Login");
        MechLoginFromSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MechLoginFromSignUpActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sign-Up For Mechanic New Account");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mechanism.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MechPhone)
                    .addComponent(MechEmail)
                    .addComponent(MechUserName)
                    .addComponent(MechShopName)
                    .addComponent(MechPassword)
                    .addComponent(MechPinCode)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(MechCreateAC, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(MechSignUpHome, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(39, 39, 39)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MechSigninExit, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MechLoginFromSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(84, 84, 84)
                .addComponent(jLabel9)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MechUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MechEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MechPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MechShopName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MechPinCode, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MechPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MechCreateAC, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MechSignUpHome, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MechSigninExit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MechLoginFromSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MechPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MechPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MechPhoneActionPerformed

    private void MechPinCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MechPinCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MechPinCodeActionPerformed

    private void MechPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MechPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MechPasswordActionPerformed

    private void MechSignUpHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MechSignUpHomeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
            new index().setVisible(true);
    }//GEN-LAST:event_MechSignUpHomeActionPerformed

    private void MechUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MechUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MechUserNameActionPerformed

    private void MechEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MechEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MechEmailActionPerformed

    private void MechCreateACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MechCreateACActionPerformed
        String mechname=MechUserName.getText(); // TODO add ySour handling code here:
        String mechid=MechEmail.getText();
        String phoneno=MechPhone.getText();
        String shopname=MechShopName.getText();
        String pin=MechPinCode.getText();
        String password=MechPassword.getText();
        try
        {
            Connection con=ConnectionProvider.getcon();
            Statement st=con.createStatement();
            st.executeUpdate("insert into mechanic values('"+mechname+"','"+mechid+"','"+phoneno+"','"+shopname+"','"+pin+"','"+password+"')");
            JOptionPane.showMessageDialog(null,"Successfully updated");
            setVisible(false);
            new MechanicService().setVisible(true);

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
            setVisible(false);
            new MechanicSignUp().setVisible(true);

        }

    }//GEN-LAST:event_MechCreateACActionPerformed

    private void MechShopNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MechShopNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MechShopNameActionPerformed

    private void MechSigninExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MechSigninExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MechSigninExitActionPerformed

    private void MechLoginFromSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MechLoginFromSignUpActionPerformed
        // TODO add your handling code here:
        setVisible(false);
            new MechanicLogin().setVisible(true);
    }//GEN-LAST:event_MechLoginFromSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MechanicSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MechanicSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MechanicSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MechanicSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MechanicSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MechCreateAC;
    private javax.swing.JTextField MechEmail;
    private javax.swing.JButton MechLoginFromSignUp;
    private javax.swing.JTextField MechPassword;
    private javax.swing.JTextField MechPhone;
    private javax.swing.JTextField MechPinCode;
    private javax.swing.JTextField MechShopName;
    private javax.swing.JButton MechSignUpHome;
    private javax.swing.JButton MechSigninExit;
    private javax.swing.JTextField MechUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
