/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import project1.ConnectionProvider;
import javax.swing.JOptionPane;
import com.mysql.jdbc.PreparedStatement;
/**
 *
 * @author Shiva
 */
public class TwoWheeler extends javax.swing.JFrame {

    /**
     * Creates new form TwoWheeler
     */
    public TwoWheeler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TwoWheeleUserVehicleNumber = new javax.swing.JTextField();
        TwoWheeleUserVehicleModel = new javax.swing.JTextField();
        TwoWheeleUserDrivingLicence = new javax.swing.JTextField();
        TypeVehicle2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CreateTwoWheeleDetail = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Two Wheeler Vehicle Detail");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Driving Licence");

        TwoWheeleUserVehicleNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoWheeleUserVehicleNumberActionPerformed(evt);
            }
        });

        TwoWheeleUserVehicleModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoWheeleUserVehicleModelActionPerformed(evt);
            }
        });

        TwoWheeleUserDrivingLicence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoWheeleUserDrivingLicenceActionPerformed(evt);
            }
        });

        TypeVehicle2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gear", "Gearless" }));
        TypeVehicle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeVehicle2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Vehicle Number");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Model");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Type");

        CreateTwoWheeleDetail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CreateTwoWheeleDetail.setText("Done");
        CreateTwoWheeleDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateTwoWheeleDetailActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bike.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CreateTwoWheeleDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TypeVehicle2, 0, 359, Short.MAX_VALUE)
                    .addComponent(TwoWheeleUserVehicleNumber)
                    .addComponent(TwoWheeleUserVehicleModel)
                    .addComponent(TwoWheeleUserDrivingLicence))
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addContainerGap(66, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TwoWheeleUserVehicleNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TypeVehicle2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TwoWheeleUserVehicleModel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TwoWheeleUserDrivingLicence, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addComponent(CreateTwoWheeleDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(0, 50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TypeVehicle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeVehicle2ActionPerformed
  // TODO add your handling code here:
    }//GEN-LAST:event_TypeVehicle2ActionPerformed

    private void CreateTwoWheeleDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateTwoWheeleDetailActionPerformed
        String vno=TwoWheeleUserVehicleNumber.getText(); // TODO add ySour handling code here:
        String type=TypeVehicle2.getSelectedItem().toString();;
        String model=TwoWheeleUserVehicleModel.getText();
        String usdl=TwoWheeleUserDrivingLicence.getText();
        try
        {
            Connection con=ConnectionProvider.getcon();
            Statement st=con.createStatement();
            st.executeUpdate("insert into vehiclet values('"+vno+"','"+type+"','"+model+"','"+usdl+"')");
            JOptionPane.showMessageDialog(null,"Successfully updated");
            setVisible(false);
            new UserLogIn().setVisible(true);

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"licence not exist");
            setVisible(false);
            new TwoWheeler().setVisible(true);

        }
        
    }//GEN-LAST:event_CreateTwoWheeleDetailActionPerformed

    private void TwoWheeleUserVehicleNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoWheeleUserVehicleNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TwoWheeleUserVehicleNumberActionPerformed

    private void TwoWheeleUserVehicleModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoWheeleUserVehicleModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TwoWheeleUserVehicleModelActionPerformed

    private void TwoWheeleUserDrivingLicenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoWheeleUserDrivingLicenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TwoWheeleUserDrivingLicenceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TwoWheeler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TwoWheeler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TwoWheeler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TwoWheeler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TwoWheeler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateTwoWheeleDetail;
    private javax.swing.JTextField TwoWheeleUserDrivingLicence;
    private javax.swing.JTextField TwoWheeleUserVehicleModel;
    private javax.swing.JTextField TwoWheeleUserVehicleNumber;
    private javax.swing.JComboBox<String> TypeVehicle2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
