
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import project1.ConnectionProvider;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shiva
 */
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        updatemech = new javax.swing.JTable();
        UpdateMech = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MechUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        MechEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        MechPhone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        MechShopName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        MechPinCode = new javax.swing.JTextField();
        BackFromUpdate = new javax.swing.JButton();
        DisplayMech = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        updatemech.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "mechanic name", "mechanic id", "mechanic shop", "mechanic phone", "mechanic pin"
            }
        ));
        jScrollPane1.setViewportView(updatemech);

        UpdateMech.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdateMech.setText("Update");
        UpdateMech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateMechActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Full Name");

        MechUserName.setBackground(new java.awt.Color(255, 255, 204));
        MechUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MechUserNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Licence No. To Update");

        MechEmail.setBackground(new java.awt.Color(255, 255, 204));
        MechEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MechEmailActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Phone number");

        MechPhone.setBackground(new java.awt.Color(255, 255, 204));
        MechPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MechPhoneActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Shop Name");

        MechShopName.setBackground(new java.awt.Color(255, 255, 204));
        MechShopName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MechShopNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Pin/Zip Code");

        MechPinCode.setBackground(new java.awt.Color(255, 255, 204));
        MechPinCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MechPinCodeActionPerformed(evt);
            }
        });

        BackFromUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BackFromUpdate.setText("Back");
        BackFromUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackFromUpdateActionPerformed(evt);
            }
        });

        DisplayMech.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DisplayMech.setText("Display");
        DisplayMech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayMechActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Update Mechanic");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(MechPinCode, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MechShopName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MechPhone, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MechUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MechEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UpdateMech, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DisplayMech, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BackFromUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UpdateMech, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DisplayMech, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BackFromUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MechEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MechUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MechPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MechShopName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MechPinCode, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MechUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MechUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MechUserNameActionPerformed

    private void MechEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MechEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MechEmailActionPerformed

    private void MechPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MechPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MechPhoneActionPerformed

    private void MechShopNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MechShopNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MechShopNameActionPerformed

    private void MechPinCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MechPinCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MechPinCodeActionPerformed

    private void BackFromUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackFromUpdateActionPerformed
        // TODO add your handling code here:
        setVisible(false);
            new Admin().setVisible(true);
    }//GEN-LAST:event_BackFromUpdateActionPerformed

    private void UpdateMechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateMechActionPerformed
       String mechname=MechUserName.getText(); // TODO add ySour handling code here:
        String mechid=MechEmail.getText();
        String phoneno=MechPhone.getText();
        String shopname=MechShopName.getText();
        String pin=MechPinCode.getText();
        try
        {
            Connection con=ConnectionProvider.getcon();
            Statement st=con.createStatement();
            st.executeUpdate("update mechanic set mechname='"+mechname+"',mechid='"+mechid+"',phoneno='"+phoneno+"',shopname='"+shopname+"',pin='"+pin+"'where mechid='"+mechid+"'");
            JOptionPane.showMessageDialog(null,"Successfully updated");
            Statement stt=con.createStatement();
             ResultSet rs=stt.executeQuery("select mechname as mechanic_name,mechid as mechanic_licence,shopname as mechanic_shop,phoneno as mechanic_phone,pin as pincode from mechanic");
             updatemech.setModel(DbUtils.resultSetToTableModel(rs));
            

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"not connected");
            setVisible(false);
            new Update().setVisible(true);

        } // TODO add your handling code here:
    }//GEN-LAST:event_UpdateMechActionPerformed

    private void DisplayMechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayMechActionPerformed
      try
        {
            Connection con=ConnectionProvider.getcon();
            Statement st=con.createStatement();
            ResultSet rs = st.executeQuery("select mechname as mechanic_name,mechid as mechanic_licence,shopname as mechanic_shop,phoneno as mechanic_phone,pin as pincode from mechanic");
           updatemech.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"CONNECTION NOT ESATABLISHED");
        }  // TODO add your handling code here:
    }//GEN-LAST:event_DisplayMechActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackFromUpdate;
    private javax.swing.JButton DisplayMech;
    private javax.swing.JTextField MechEmail;
    private javax.swing.JTextField MechPhone;
    private javax.swing.JTextField MechPinCode;
    private javax.swing.JTextField MechShopName;
    private javax.swing.JTextField MechUserName;
    private javax.swing.JButton UpdateMech;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable updatemech;
    // End of variables declaration//GEN-END:variables
}
